name: Docker Image CI

on: [pull_request]
jobs:

  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup
      run: |
        docker pull regehr/souperweb:latest
        docker run -it -d --name souperweb regehr/souperweb bash
        docker cp . souperweb:/data/
        docker exec souperweb ln -s /usr/src/souper/third_party/

    - name: Build
      run: |
        docker exec souperweb mkdir build
        docker exec --user root souperweb /bin/bash -c "cd /data/build && cmake -DCMAKE_CXX_FLAGS='-Werror' -DTEST_SOLVER=-z3-path=/usr/src/souper/third_party/z3/build/z3 -DTEST_SYNTHESIS=ON -DTEST_LONG_DURATION_SYNTHESIS=OFF -DCMAKE_BUILD_TYPE=Release .."
        docker exec --user root souperweb /bin/bash -c "cd /data/build && export GOPATH=/usr/src/go && make"
        docker exec --user root souperweb /bin/bash -c "cd /data/build && LIT_ARGS='-v -vv' ./run_lit"
    
    - name: Verify
      env: 
        API_HEADER: "Accept: application/vnd.github.v3+json; application/vnd.github.antiope-preview+json"
        AUTH_HEADER: "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
        URI: "https://api.github.com"
      run: |
        export NUMBER=$(cat "${{ github.event_path }}" | grep number | grep -o '[0-9]*')
        docker exec --user root souperweb /bin/bash -c "cd /data/build && python3 check_enumerative_guesses.py > enum_output.txt"
        docker cp souperweb:/data/build/enum_output.txt .
        export ENUM_OUTPUT=$(cat enum_output.txt)
        curl -sSL -H "$AUTH_HEADER" -H "$API_HEADER" -d '{"body":"$ENUM_OUTPUT"}' -H "Content-Type: application/json" -X POST "$URI/repos/${{ github.repository }}/issues/$NUMBER/comments"
